---
- name: Install MYSQL and start service
  hosts: database
  vars_files:
    - database_default.yml
  tasks:
    - name: Install MySQL-server
      apt:
         name: mysql-server
         state: latest

    - name: Intsall python-mysqldb
      apt:
         name: python-mysqldb
         state: latest

    - name: Intsall python-mysqldb
      apt:
         name: python3-pymysql
         state: latest

    - name: replace line
      lineinfile:
        path:  /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '127.0.0.1'
        line: 'bind-address            = 0.0.0.0'
        backrefs: yes

    - name: Run the command restart mysql
      command: sudo systemctl restart mysql

    - name: Run the command for firewall
      command: sudo iptables -A INPUT -p tcp --dport 3306 -j ACCEPT


  # MySQL Configuration
    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
      tags: [ mysql, mysql-root ]
    

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_user }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL,GRANT"
        host: "{{ remote_host_ip }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: MySQL table
      copy:
        src: wordpress_latest.db
        dest: /tmp/wordpress_latest.db

    - name: Inert table MySQL
      mysql_db: 
        name: "{{ mysql_db }}" 
        state: import 
        target: /tmp/wordpress_latest.db
        login_user: root
        login_password: "{{ mysql_root_password }}"

